from django.urls import path

from .views import (
    ai_chat_view,
    ai_chat_stream_view,
    ai_thread_delete_view,
    ai_thread_messages_view,
    ai_thread_rename_view,
    ai_threads_view,
    course_assignment_create_view,
    dashboard_view,
    grade_report_predict_view,
    grade_report_view,
    login_view,
    library_application_submit_view,
    library_applications_view,
    registration_delete_view,
    registration_list_view,
    registration_submit_view,
    registration_update_view,
    logout_view,
    session_view,
    students_by_class_view,
    teacher_mark_upsert_view,
    teacher_marks_view,
    teacher_students_view,
    weekly_schedule_view,
)

urlpatterns = [
    path("login/", login_view, name="api-login"),
    path("logout/", logout_view, name="api-logout"),
    path("session/", session_view, name="api-session"),
    path("dashboard/", dashboard_view, name="api-dashboard"),
    path("ai/threads/", ai_threads_view, name="api-ai-threads"),
    path("ai/threads/<int:thread_id>/messages/", ai_thread_messages_view, name="api-ai-thread-messages"),
    path("ai/threads/<int:thread_id>/rename/", ai_thread_rename_view, name="api-ai-thread-rename"),
    path("ai/threads/<int:thread_id>/delete/", ai_thread_delete_view, name="api-ai-thread-delete"),
    path("ai/chat/", ai_chat_view, name="api-ai-chat"),
    path("ai/chat/stream/", ai_chat_stream_view, name="api-ai-chat-stream"),
    path("grade-report/", grade_report_view, name="api-grade-report"),
    path("grade-report/predict/", grade_report_predict_view, name="api-grade-report-predict"),
    path("registration/submit/", registration_submit_view, name="api-registration-submit"),
    path("registration/list/", registration_list_view, name="api-registration-list"),
    path("registration/<int:profile_id>/update/", registration_update_view, name="api-registration-update"),
    path("registration/<int:profile_id>/delete/", registration_delete_view, name="api-registration-delete"),
    path("courses/assign/", course_assignment_create_view, name="api-courses-assign"),
    path("schedule/weekly/", weekly_schedule_view, name="api-schedule-weekly"),
    path("students/by-class/", students_by_class_view, name="api-students-by-class"),
    path("teacher/students/", teacher_students_view, name="api-teacher-students"),
    path("teacher/marks/", teacher_marks_view, name="api-teacher-marks"),
    path("teacher/marks/upsert/", teacher_mark_upsert_view, name="api-teacher-marks-upsert"),
    path("library/applications/submit/", library_application_submit_view, name="api-library-application-submit"),
    path("library/applications/", library_applications_view, name="api-library-applications"),
]
