# Generated by Django 6.0.4 on 2026-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registrationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
