# Generated by Django 6.0.4 on 2026-04-22 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseassignment_weeklyclassschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='teacher_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_domain_assignments', to='core.smartuser'),
        ),
        migrations.CreateModel(
            name='StudentSubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('ct_1', models.IntegerField(default=0)),
                ('ct_2', models.IntegerField(default=0)),
                ('ct_3', models.IntegerField(default=0)),
                ('ct_4', models.IntegerField(default=0)),
                ('ct_5', models.IntegerField(default=0)),
                ('ct_6', models.IntegerField(default=0)),
                ('ct_7', models.IntegerField(default=0)),
                ('ct_8', models.IntegerField(default=0)),
                ('term_1', models.IntegerField(default=0)),
                ('term_2', models.IntegerField(default=0)),
                ('model_1', models.IntegerField(default=0)),
                ('model_2', models.IntegerField(default=0)),
                ('model_3', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='core.smartuser')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_marks', to='core.smartuser')),
            ],
            options={
                'ordering': ['subject', 'id'],
                'unique_together': {('teacher', 'student', 'subject')},
            },
        ),
    ]
