# Generated by Django 6.0.4 on 2026-04-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_courseassignment_teacher_user_studentsubjectmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_role', models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Management')])),
                ('resource_type', models.CharField(max_length=80)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_applications', to='core.smartuser')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
